class Client < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :orders
  
  # validations ...............................................................
  validates :cellphone, uniqueness: true
  validates :name, presence: true
  validates :age, presence: true
  validates :gender, presence: true
  validates :address, presence: true
  validates :email, presence: true

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
