class Order < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :client
  belongs_to :user
  has_one :card

  # validations ...............................................................
  validates :status, presence: true
  validates :client_id, presence: true

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  default_value_for :is_paid, false
  default_value_for :is_performed, false

  # class methods .............................................................
  # public instance methods ...................................................
  def status_chs
    return "未付款" if status == "none"
    "已付款" if status == "full"
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
end
